updated scripts and added update mechanic

diff --git a/url b/url
--- a/url
+++ b/url
@@ -2,107 +2,107 @@
 #--------------------------------------------
 set -Eeuo pipefail
 if [[ -n "${DEBUG:-}" ]]; then
-  set -x
+	set -x
 fi
 trap stack_trace ERR
 function stack_trace() {
-  echo -e "\nThe command '$BASH_COMMAND' triggerd a stacktrace:\nStack Trace:"
-  for (( i = 1; i < ${#FUNCNAME[@]}; i++ )); do
-  echo "    ($i) ${FUNCNAME[$i]:-(top level)} ${BASH_SOURCE[$i]:-(no file)}:${BASH_LINENO[$(( i - 1 ))]}"
-  done
+	echo -e "\nThe command '$BASH_COMMAND' triggerd a stacktrace:\nStack Trace:"
+	for ((i = 1; i < ${#FUNCNAME[@]}; i++)); do
+		echo "    ($i) ${FUNCNAME[$i]:-(top level)} ${BASH_SOURCE[$i]:-(no file)}:${BASH_LINENO[$((i - 1))]}"
+	done
 }
-error(){ printf "\e[1;31m[ERROR]\e[0m %s\n" "${1:-error message missing}" && trap true ERR && return 1; }
-warning(){ printf "\e[1;33m[WARNING]\e[0m %s\n" "$1" >&2; }
-success(){ printf "\e[1;32m[SUCCESS]\e[0m %s\n" "$1" >&2; }
-info(){ printf "\e[1;34m[INFO]\e[0m %s\n" "$1" >&2; }
-green(){ if [[ -t 0 ]]; then printf "\e[1;32m%s\e[0m" "$1"; else printf "%s" "$1"; fi }
-red(){ if [[ -t 0 ]]; then printf "\e[1;31m%s\e[0m" "$1"; else printf "%s" "$1"; fi }
-blue(){ if [[ -t 0 ]]; then printf "\e[1;34m%s\e[0m" "$1"; else printf "%s" "$1"; fi }
+error() { printf "\e[1;31m[ERROR]\e[0m %s\n" "${1:-error message missing}" && trap true ERR && return 1; }
+warning() { printf "\e[1;33m[WARNING]\e[0m %s\n" "$1" >&2; }
+success() { printf "\e[1;32m[SUCCESS]\e[0m %s\n" "$1" >&2; }
+info() { printf "\e[1;34m[INFO]\e[0m %s\n" "$1" >&2; }
+green() { if [[ -t 0 ]]; then printf "\e[1;32m%s\e[0m" "$1"; else printf "%s" "$1"; fi; }
+red() { if [[ -t 0 ]]; then printf "\e[1;31m%s\e[0m" "$1"; else printf "%s" "$1"; fi; }
+blue() { if [[ -t 0 ]]; then printf "\e[1;34m%s\e[0m" "$1"; else printf "%s" "$1"; fi; }
 SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 export SCRIPT_DIR
 #--------------------------------------------
 declare -A url__commands
 declare -A url__command_descriptions
-url::desc(){
-  url__commands["$1"]="$1"
-  url__command_descriptions["$1"]="$2"
+url::desc() {
+	url__commands["$1"]="$1"
+	url__command_descriptions["$1"]="$2"
 }
 declare -A url__aliases
-url::alias(){
-  url__aliases["$1"]+="|$2"
-  url__commands["$2"]="$1"
+url::alias() {
+	url__aliases["$1"]+="|$2"
+	url__commands["$2"]="$1"
 }
 url::desc help "Show this help message"
-url::help(){
-  case "${1:-list}" in
-    */)
-      printf "Group Commands for %s:\n" "$(green "${1}")"
-      for key in "${!url__command_descriptions[@]}"; do
-        if [[ "$key" == "${1}"?* ]]; then
-          local name_without_group="${key:${#1}}"
-          if [[ ( ! "$name_without_group" == */* ) \
-             || "$name_without_group" =~ ^[a-zA-Z0-9]+/$ ]]; then
-            if [[ -v url__aliases[$key] ]]; then
-              printf "  %s: %s\n" \
-                     "$(green "$key${url__aliases[$key]}")" \
-                     "${url__command_descriptions[$key]}"
-            else
-              printf "  %s: %s\n" \
-                     "$(green "$key")" \
-                     "${url__command_descriptions[$key]}"
-            fi
-          fi
-        fi
-      done
-      ;;
-    list)
-      echo "Usage: url [command]"
-      echo "Commands:"
-      for key in "${!url__command_descriptions[@]}"; do
-        if [[ ( ! "$key" == */* ) \
-           || "$key" =~ ^[a-zA-Z0-9_.-]+/$ ]]; then
-          if [[ -v url__aliases[$key] ]]; then
-            printf "  %s: %s\n" \
-                   "$(green "$key${url__aliases[$key]}")" \
-                   "${url__command_descriptions[$key]}"
-          else
-            printf "  %s: %s\n" \
-                   "$(green "$key")" \
-                   "${url__command_descriptions[$key]}"
-          fi
-        fi
-      done
-      ;;
-    *)
-      if [[ -v url__command_descriptions[$1] ]]; then
-        printf "Usage: url %s\n" "$(green "$1")"
-        if [[ -v url__aliases[$1] ]]; then
-          printf "Aliases: %s\n" "$(green "${url__aliases[$1]//|/ }")"
-        fi
-        printf "%s\n" "${url__command_descriptions[$1]}"
-      else
-        error "Unknown command: $1"
-      fi
-      ;;
-  esac
+url::help() {
+	case "${1:-list}" in
+	*/)
+		printf "Group Commands for %s:\n" "$(green "${1}")"
+		for key in "${!url__command_descriptions[@]}"; do
+			if [[ "$key" == "${1}"?* ]]; then
+				local name_without_group="${key:${#1}}"
+				if [[ (! "$name_without_group" == */*) ||
+					"$name_without_group" =~ ^[a-zA-Z0-9]+/$ ]]; then
+					if [[ -v url__aliases[$key] ]]; then
+						printf "  %s: %s\n" \
+							"$(green "$key${url__aliases[$key]}")" \
+							"${url__command_descriptions[$key]}"
+					else
+						printf "  %s: %s\n" \
+							"$(green "$key")" \
+							"${url__command_descriptions[$key]}"
+					fi
+				fi
+			fi
+		done
+		;;
+	list)
+		echo "Usage: url [command]"
+		echo "Commands:"
+		for key in "${!url__command_descriptions[@]}"; do
+			if [[ (! "$key" == */*) ||
+				"$key" =~ ^[a-zA-Z0-9_.-]+/$ ]]; then
+				if [[ -v url__aliases[$key] ]]; then
+					printf "  %s: %s\n" \
+						"$(green "$key${url__aliases[$key]}")" \
+						"${url__command_descriptions[$key]}"
+				else
+					printf "  %s: %s\n" \
+						"$(green "$key")" \
+						"${url__command_descriptions[$key]}"
+				fi
+			fi
+		done
+		;;
+	*)
+		if [[ -v url__command_descriptions[$1] ]]; then
+			printf "Usage: url %s\n" "$(green "$1")"
+			if [[ -v url__aliases[$1] ]]; then
+				printf "Aliases: %s\n" "$(green "${url__aliases[$1]//|/ }")"
+			fi
+			printf "%s\n" "${url__command_descriptions[$1]}"
+		else
+			error "Unknown command: $1"
+		fi
+		;;
+	esac
 }
 
-url(){
-  local base_zero
-  base_zero="$(basename "$0")"
-  if [[ "$base_zero" = "url" ]]; then
-    command="${1:-help}"
-    shift || true
-  else
-    command="$base_zero"
-  fi
-  if [[ "$command" == */ ]]; then
-    "url::help" "$command" "$@"
-  elif [[ -v url__commands[$command] ]]; then
-    "url::${url__commands[$command]}" "$@"
-  else
-    error "Unknown command: $command"
-  fi
+url() {
+	local base_zero
+	base_zero="$(basename "$0")"
+	if [[ "$base_zero" = "url" ]]; then
+		command="${1:-help}"
+		shift || true
+	else
+		command="$base_zero"
+	fi
+	if [[ "$command" == */ ]]; then
+		"url::help" "$command" "$@"
+	elif [[ -v url__commands[$command] ]]; then
+		"url::${url__commands[$command]}" "$@"
+	else
+		error "Unknown command: $command"
+	fi
 }
 
 # shellcheck disable=SC2016
@@ -137,76 +137,121 @@ def urlparse:
 
 ######################################### Commands ##########################################
 url::desc parse "Parse a URL"
-url::parse(){
-  local URI output
-  output="json"
-  while [[ "$#" -gt 0 ]]; do
-    case "$1" in
-      -h|--help)
-        echo "Usage: url parse [options] <URI>"
-        echo "Options:"
-        echo "  -f, --format <format>  Output format (default: json)"
-        echo "               Available formats: json, bash, sh"
-        return 0
-        ;;
-      -f|--format)
-        output="$2"
-        shift
-        ;;
-      *)
-        URI="$1"
-        ;;
-    esac
-    shift
-  done
-  parsed="$(echo "$URI" | jq -R "$url_jq_urlparse"urlparse)"
-  case "$output" in
-    json)
-      echo "$parsed"
-      ;;
-    bash|sh)
-      scheme="$(echo "$parsed" | jq -r '.scheme')"
-      authority="$(echo "$parsed" | jq -r '.authority')"
-      domain="$(echo "$parsed" | jq -r '.domain')"
-      port="$(echo "$parsed" | jq -r '.port')"
-      path="$(echo "$parsed" | jq -r '.path')"
-      declare -A query
-      while IFS= read -r -d '' key; do
-        value="$(echo "$parsed" | jq -r ".query[\"$key\"]")"
-        query["$key"]="$value"
-      done < <(echo "$parsed" | jq -r '.query | keys[]' | tr '\n' '\0')
-      fragment="$(echo "$parsed" | jq -r '.fragment')"
-      case "$output" in
-        bash)
-          echo "scheme=\"$scheme\""
-          echo "authority=\"$authority\""
-          echo "domain=\"$domain\""
-          echo "port=\"$port\""
-          echo "path=\"$path\""
-          for key in "${!query[@]}"; do
-            echo "query[\"$key\"]=\"${query[$key]}\""
-          done
-          echo "fragment=\"$fragment\""
-          ;;
-        sh)
-          echo "export scheme=\"$scheme\""
-          echo "export authority=\"$authority\""
-          echo "export domain=\"$domain\""
-          echo "export port=\"$port\""
-          echo "export path=\"$path\""
-          for key in "${!query[@]}"; do
-            echo "export query_$key=\"${query[$key]}\""
-          done
-          echo "export fragment=\"$fragment\""
-          ;;
-      esac;;
-    *)
-      error "Unknown output format: $output"
-      ;;
-  esac
+url::parse() {
+	local URI output
+	output="json"
+	while [[ "$#" -gt 0 ]]; do
+		case "$1" in
+		-h | --help)
+			echo "Usage: url parse [options] <URI>"
+			echo "Options:"
+			echo "  -f, --format <format>  Output format (default: json)"
+			echo "               Available formats: json, bash, sh"
+			return 0
+			;;
+		-f | --format)
+			output="$2"
+			shift
+			;;
+		*)
+			URI="$1"
+			;;
+		esac
+		shift
+	done
+	parsed="$(echo "$URI" | jq -R "$url_jq_urlparse"urlparse)"
+	case "$output" in
+	json)
+		echo "$parsed"
+		;;
+	bash | sh)
+		scheme="$(echo "$parsed" | jq -r '.scheme')"
+		authority="$(echo "$parsed" | jq -r '.authority')"
+		domain="$(echo "$parsed" | jq -r '.domain')"
+		port="$(echo "$parsed" | jq -r '.port')"
+		path="$(echo "$parsed" | jq -r '.path')"
+		declare -A query
+		while IFS= read -r -d '' key; do
+			value="$(echo "$parsed" | jq -r ".query[\"$key\"]")"
+			query["$key"]="$value"
+		done < <(echo "$parsed" | jq -r '.query | keys[]' | tr '\n' '\0')
+		fragment="$(echo "$parsed" | jq -r '.fragment')"
+		case "$output" in
+		bash)
+			echo "scheme=\"$scheme\""
+			echo "authority=\"$authority\""
+			echo "domain=\"$domain\""
+			echo "port=\"$port\""
+			echo "path=\"$path\""
+			for key in "${!query[@]}"; do
+				echo "query[\"$key\"]=\"${query[$key]}\""
+			done
+			echo "fragment=\"$fragment\""
+			;;
+		sh)
+			echo "export scheme=\"$scheme\""
+			echo "export authority=\"$authority\""
+			echo "export domain=\"$domain\""
+			echo "export port=\"$port\""
+			echo "export path=\"$path\""
+			for key in "${!query[@]}"; do
+				echo "export query_$key=\"${query[$key]}\""
+			done
+			echo "export fragment=\"$fragment\""
+			;;
+		esac
+		;;
+	*)
+		error "Unknown output format: $output"
+		;;
+	esac
+}
+
+url::desc encode "Encode a string to URL format"
+url::encode() {
+	local string=""
+	while [[ "$#" -gt 0 ]]; do
+		case "$1" in
+		-h | --help)
+			echo "Usage: url encode <string>"
+			return 0
+			;;
+		*)
+			if [[ -n "$string" ]]; then
+				string+=" $1"
+			else
+				string="$1"
+			fi
+			;;
+		esac
+		shift
+	done
+	echo -n "$string" | jq -sRr '@uri'
+}
+
+url::desc decode "Decode a URL encoded string"
+url::decode() {
+	local string=""
+	while [[ "$#" -gt 0 ]]; do
+		case "$1" in
+		-h | --help)
+			echo "Usage: url decode <string>"
+			return 0
+			;;
+		*)
+			if [[ -n "$string" ]]; then
+				string+=" $1"
+			else
+				string="$1"
+			fi
+			;;
+		esac
+		shift
+	done
+	echo "$string" | jq -Rr "$url_jq_urlparse"urldecode
 }
 
 # Run main if not sourced
 if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
-    url "$@"
+	url "$@"
 fi
diff --git a/yggstack b/yggstack
--- a/yggstack
+++ b/yggstack
@@ -7,94 +7,97 @@ fi
 trap stack_trace ERR
 function stack_trace() {
   echo -e "\nThe command '$BASH_COMMAND' triggerd a stacktrace:\nStack Trace:"
-  for (( i = 1; i < ${#FUNCNAME[@]}; i++ )); do
-  echo "    ($i) ${FUNCNAME[$i]:-(top level)} ${BASH_SOURCE[$i]:-(no file)}:${BASH_LINENO[$(( i - 1 ))]}"
+  for ((i = 1; i < ${#FUNCNAME[@]}; i++)); do
+    echo "    ($i) ${FUNCNAME[$i]:-(top level)} ${BASH_SOURCE[$i]:-(no file)}:${BASH_LINENO[$((i - 1))]}"
   done
 }
-error(){ printf "\e[1;31m[ERROR]\e[0m %s\n" "${1:-error message missing}" && trap true ERR && return 1; }
-warning(){ printf "\e[1;33m[WARNING]\e[0m %s\n" "$1" >&2; }
-success(){ printf "\e[1;32m[SUCCESS]\e[0m %s\n" "$1" >&2; }
-info(){ printf "\e[1;34m[INFO]\e[0m %s\n" "$1" >&2; }
-green(){ if [[ -t 0 ]]; then printf "\e[1;32m%s\e[0m" "$1"; else printf "%s" "$1"; fi }
-red(){ if [[ -t 0 ]]; then printf "\e[1;31m%s\e[0m" "$1"; else printf "%s" "$1"; fi }
-blue(){ if [[ -t 0 ]]; then printf "\e[1;34m%s\e[0m" "$1"; else printf "%s" "$1"; fi }
+error() { printf "\e[1;31m[ERROR]\e[0m %s\n" "${1:-error message missing}" && trap true ERR && return 1; }
+warning() { printf "\e[1;33m[WARNING]\e[0m %s\n" "$1" >&2; }
+success() { printf "\e[1;32m[SUCCESS]\e[0m %s\n" "$1" >&2; }
+info() { printf "\e[1;34m[INFO]\e[0m %s\n" "$1" >&2; }
+green() { if [[ -t 0 ]]; then printf "\e[1;32m%s\e[0m" "$1"; else printf "%s" "$1"; fi; }
+red() { if [[ -t 0 ]]; then printf "\e[1;31m%s\e[0m" "$1"; else printf "%s" "$1"; fi; }
+blue() { if [[ -t 0 ]]; then printf "\e[1;34m%s\e[0m" "$1"; else printf "%s" "$1"; fi; }
 SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 export SCRIPT_DIR
 #--------------------------------------------
 declare -A yggstack_setup_commands
 declare -A yggstack_setup_command_descriptions
-yggstack:desc(){
+yggstack:desc() {
   yggstack_setup_commands["$1"]="$1"
   yggstack_setup_command_descriptions["$1"]="$2"
 }
 declare -A yggstack_setup_aliases
-yggstack:alias(){
+yggstack:alias() {
   yggstack_setup_aliases["$1"]+="|$2"
   yggstack_setup_commands["$2"]="$1"
 }
 yggstack:desc help "Show this help message"
-yggstack:help(){
+yggstack:help() {
   case "${1:-list}" in
-    */)
-      printf "Group Commands for %s:\n" "$(green "${1}")"
-      for key in "${!yggstack_setup_command_descriptions[@]}"; do
-        if [[ "$key" == "${1}"?* ]]; then
-          local name_without_group="${key:${#1}}"
-          if [[ ( ! "$name_without_group" == */* ) \
-             || "$name_without_group" =~ ^[a-zA-Z0-9]+/$ ]]; then
-            if [[ -v yggstack_setup_aliases[$key] ]]; then
-              printf "  %s: %s\n" \
-                     "$(green "$key${yggstack_setup_aliases[$key]}")" \
-                     "${yggstack_setup_command_descriptions[$key]}"
-            else
-              printf "  %s: %s\n" \
-                     "$(green "$key")" \
-                     "${yggstack_setup_command_descriptions[$key]}"
-            fi
-          fi
-        fi
-      done
-      ;;
-    list)
-      echo "Usage: yggstack [command]"
-      echo "Commands:"
-      for key in "${!yggstack_setup_command_descriptions[@]}"; do
-        if [[ ( ! "$key" == */* ) \
-           || "$key" =~ ^[a-zA-Z0-9_.-]+/$ ]]; then
+  */)
+    printf "Group Commands for %s:\n" "$(green "${1}")"
+    for key in "${!yggstack_setup_command_descriptions[@]}"; do
+      if [[ "$key" == "${1}"?* ]]; then
+        local name_without_group="${key:${#1}}"
+        if [[ (! "$name_without_group" == */*) ||
+          "$name_without_group" =~ ^[a-zA-Z0-9]+/$ ]]; then
           if [[ -v yggstack_setup_aliases[$key] ]]; then
             printf "  %s: %s\n" \
-                   "$(green "$key${yggstack_setup_aliases[$key]}")" \
-                   "${yggstack_setup_command_descriptions[$key]}"
+              "$(green "$key${yggstack_setup_aliases[$key]}")" \
+              "${yggstack_setup_command_descriptions[$key]}"
           else
             printf "  %s: %s\n" \
-                   "$(green "$key")" \
-                   "${yggstack_setup_command_descriptions[$key]}"
+              "$(green "$key")" \
+              "${yggstack_setup_command_descriptions[$key]}"
           fi
         fi
-      done
-      ;;
-    *)
-      if [[ -v yggstack_setup_command_descriptions[$1] ]]; then
-        printf "Usage: yggstack %s\n" "$(green "$1")"
-        if [[ -v yggstack_setup_aliases[$1] ]]; then
-          printf "Aliases: %s\n" "$(green "${yggstack_setup_aliases[$1]//|/ }")"
-        fi
-        printf "%s\n" "${yggstack_setup_command_descriptions[$1]}"
-      else
-        error "Unknown command: $1"
       fi
-      ;;
+    done
+    ;;
+  list)
+    echo "Usage: yggstack [command]"
+    echo "Commands:"
+    for key in "${!yggstack_setup_command_descriptions[@]}"; do
+      if [[ (! "$key" == */*) ||
+        "$key" =~ ^[a-zA-Z0-9_.-]+/$ ]]; then
+        if [[ -v yggstack_setup_aliases[$key] ]]; then
+          printf "  %s: %s\n" \
+            "$(green "$key${yggstack_setup_aliases[$key]}")" \
+            "${yggstack_setup_command_descriptions[$key]}"
+        else
+          printf "  %s: %s\n" \
+            "$(green "$key")" \
+            "${yggstack_setup_command_descriptions[$key]}"
+        fi
+      fi
+    done
+    ;;
+  *)
+    if [[ -v yggstack_setup_command_descriptions[$1] ]]; then
+      printf "Usage: yggstack %s\n" "$(green "$1")"
+      if [[ -v yggstack_setup_aliases[$1] ]]; then
+        printf "Aliases: %s\n" "$(green "${yggstack_setup_aliases[$1]//|/ }")"
+      fi
+      printf "%s\n" "${yggstack_setup_command_descriptions[$1]}"
+    else
+      error "Unknown command: $1"
+    fi
+    ;;
   esac
 }
 
 ######################################### Commands ##########################################
 yggstack:desc genconf "Generate configuration files for yggdrasil"
-yggstack:genconf(){
+yggstack:genconf() {
   if [[ ! -f ~/.cache/yggstack ]]; then
     yggstack:bin/install
   fi
   mkdir -p ~/.config
-  ~/.cache/yggstack -genconf -json | jq '.Peers=["tcp://178.27.75.49:6552", "tls://ygg.mkg20001.io:443", "tls://ygg-uplink.thingylabs.io:443"] | .AdminListen = "unix://"+$HOME+"/.config/yggstack.sock"' --arg HOME "$HOME" > ~/.config/yggstack.json
+  if ! command -v jq &>/dev/null; then
+    error "jq is required for this command"
+  fi
+  ~/.cache/yggstack -genconf -json | jq '.Peers=["tcp://178.27.75.49:6552", "tls://ygg.mkg20001.io:443", "tls://ygg-uplink.thingylabs.io:443"] | .AdminListen = "unix://"+$HOME+"/.config/yggstack.sock"' --arg HOME "$HOME" >~/.config/yggstack.json
 }
 
 yggstack_systemd_service='
@@ -112,48 +115,65 @@ RestartSec=3
 WantedBy=multi-user.target'
 yggstack:desc systemd/ "Yggstack systemd commands"
 yggstack:desc systemd/init "Initialize systemd services"
-yggstack:systemd/init(){
+yggstack:systemd/init() {
   mkdir -p ~/.config/systemd/user
-  echo "$yggstack_systemd_service" > ~/.config/systemd/user/yggstack.service
+  echo "$yggstack_systemd_service" >~/.config/systemd/user/yggstack.service
   systemctl --user daemon-reload
 }
 
 yggstack:desc systemd/start "Start systemd services"
-yggstack:systemd/start(){
+yggstack:systemd/start() {
   systemctl --user enable --now yggstack
 }
 
 yggstack:desc bin/ "Binary management"
 yggstack:desc bin/install "Install yggstack"
-yggstack:bin/install(){
+yggstack:bin/install() {
   mkdir -p ~/.local/bin
   declare OS ARCH SUFFIX
   OS=$(uname -s | tr '[:upper:]' '[:lower:]')
   SUFFIX=""
   case "$OS" in
-    linux) OS=linux;;
-    darwin) OS=darwin;;
-    android) OS=android;;
-    freebsd) OS=freebsd;;
-    netbsd) OS=netbsd;;
-    openbsd) OS=openbsd;;
-    mingw*)
-      OS=windows
-      SUFFIX=.exe;;
-    *) error "Unsupported OS: $(uname -s)";;
+  linux)
+    OS=linux
+    SUFFIX=-static
+    ;;
+  darwin)
+    OS=darwin
+    SUFFIX=-static
+    ;;
+  android) OS=android ;;
+  freebsd)
+    OS=freebsd
+    SUFFIX=-static
+    ;;
+  netbsd)
+    OS=netbsd
+    SUFFIX=-static
+    ;;
+  openbsd)
+    OS=openbsd
+    SUFFIX=-static
+    ;;
+  mingw*)
+    OS=windows
+    SUFFIX=.exe
+    ;;
+  *) error "Unsupported OS: $(uname -s)" ;;
   esac
   case "$(uname -m)" in
-    x86_64) ARCH=amd64;;
-    aarch64) ARCH=arm64;;
-    *) error "Unsupported architecture: $(uname -m)";;
+  x86_64) ARCH=amd64 ;;
+  aarch64) ARCH=arm64 ;;
+  *) error "Unsupported architecture: $(uname -m)" ;;
   esac
   info "Detected OS: $OS"
   info "Detected ARCH: $ARCH"
   info "Downloading yggstack"
-  if command -v wget &> /dev/null; then
-    wget -O ~/.cache/yggstack "https://github.com/yggdrasil-network/yggstack/releases/download/trunk/yggstack-$OS-$ARCH$SUFFIX"
-  elif command -v curl &> /dev/null; then
-    curl -o ~/.cache/yggstack -L "https://github.com/yggdrasil-network/yggstack/releases/download/trunk/yggstack-$OS-$ARCH$SUFFIX"
+  mkdir -p ~/.cache
+  if command -v wget &>/dev/null; then
+    wget -O ~/.cache/yggstack "https://github.com/yggdrasil-network/yggstack/releases/download/1.0.1/yggstack-$OS-$ARCH$SUFFIX"
+  elif command -v curl &>/dev/null; then
+    curl -o ~/.cache/yggstack -L "https://github.com/yggdrasil-network/yggstack/releases/download/1.0.1/yggstack-$OS-$ARCH$SUFFIX"
   else
     error "No download tool found"
   fi
@@ -161,7 +181,7 @@ yggstack:bin/install(){
 }
 
 yggstack:desc run "Run yggstack"
-yggstack:run(){
+yggstack:run() {
   if [[ ! -f ~/.cache/yggstack ]]; then
     yggstack:bin/install
   fi
@@ -172,12 +192,15 @@ yggstack:run(){
 }
 
 ######################################### Main ##############################################
-yggstack:main(){
-  if [[ "$(basename "$0")" = "yggstack" ]]; then
+yggstack:main() {
+  case "$(basename "$0")" in
+  yggstack | yggstack.sh)
     command="${1:-help}"
-  else
+    ;;
+  *)
     command="$(basename "$0")"
-  fi
+    ;;
+  esac
   shift || true
   if [[ "$command" == */ ]]; then
     "yggstack:help" "$command" "$@"
